### ISSUE TITLE
Streaming responses lose their Content-Length header

### ISSUE THREAD

**Issue by dpetersen** [linkerd/linkerd#1071]
I have an endpoint that returns largish (200kb) responses. When linkerd receives my response, it streams it and seems to strip out the `Content-Length` header that the original response has.

My topology is `linkerd -> nginx proxy -> Ruby app`. I was able to curl a request directly to the nginx and linkerd to diagnose that linkerd was the one modifying my response.  Here is the response that nginx returns:
```
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 14 Feb 2017 18:06:02 GMT
Content-Type: audio/mpeg
Content-Length: 205844
Last-Modified: Tue, 14 Feb 2017 18:00:51 GMT
Connection: keep-alive
Accept-Ranges: bytes
```

and here is the response that linkerd returns for the same request:

```
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 14 Feb 2017 18:06:41 GMT
Content-Type: audio/mpeg
Last-Modified: Tue, 14 Feb 2017 18:00:51 GMT
Accept-Ranges: bytes
Via: 1.1 linkerd
Transfer-Encoding: chunked
```

Note the removal of `Content-Length` and the addition of `Transfer-Encoding: chunked`.

As discussed with @olix0r, I was able to add a `streamingEnabled: false` declaration in my router config to change the behavior, but he believed that the stripping of the `Content-Length` header while streaming was a bug.

**Comment by olix0r** [comment]
Ok, digging into this a bit... linkerd is actually doing the [RFC-defined behavior](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html) with regard to removing content-length when chunking a message.
> The Content-Length header field **must not** be sent if these two lengths are different (i.e., if a Transfer-Encoding header field is present).

So the real problem is that linkerd automatically chunks these messages. I'm digging into the underlying APIs to figure out what the best course of action is.

**Comment by fantayeneh** [comment]
I did some digging, with `streamingEnabled=true`

### Nett3
It appears that the issue lies in netty message decoder.
https://github.com/netty/netty/blob/3.10/src/main/java/org/jboss/netty/handler/codec/http/HttpMessageDecoder.java#L218-L226

### Netty4
It just crashes with `Response entity too large:`.
It feels it is not honoring the `streamingEnabled` config

@olix0r 
It worth checking why with netty4 there is this issue.

@dpetersen 
if the resource you are proxying is too big, disabling `streaming` will create you problems

**Comment by olix0r** [comment]
Thanks for looking further @fantayeneh.

I believe that in netty4, the `maxChunkKB` configuration must be raised to satisfy the large request (it treats the entire message as a chunk).

I think the real problem is that when linkerd receives a large message, it automatically chunks it (because the client and server are configured with streaming).  Ideally, we wouldn't change the chunking for any messages.  However, we really really want to run our endpoints with chunking, since this allows for linkerd to process message streams without buffering. I did a bit of investigation on this last week and discovered that, as best I can tell, Netty EITHER buffers an entire message up to content-length, or it sends chunk-encoded frames. there's currently no way to read/write a partial message into/out of Netty without chunked encoding.

**Comment by adleong** [comment]
It seems like the only actionable item here would be to add an option to disable auto-chunking of large messages (without disabling streaming altogether).  Does that sound about right?

**Comment by dpetersen** [comment]
I'm cleaning up old issues of mine, and I think this qualifies. This isn't an issue for me anymore and I don't expect it to be fixed. Sorry for waiting so long to close it.
