### ISSUE TITLE
namerd Consul store retrying 404 on responses

### ISSUE THREAD

**Issue by pvcnt** [linkerd/linkerd#1105]
Hello,

I configured namerd to use a fresh Consul install as storage. As such, the `namerd/dtabs` path does not exist. If I understood well, it should cause the list() operation to return empty list. But because 404 errors are translated into a Future.exception(NotFound), it causes them to [be retried infinitely](https://github.com/linkerd/linkerd/blob/master/consul/src/main/scala/io/buoyant/consul/v1/BaseApi.scala#L35).

Moreover, I did not dig to find out why, but without any dtab saved (e.g., a fresh install), endpoints displaying dtabs are stuck (such as admin / or /api/1/dtabs).

**Comment by adleong** [comment]
Hi @pvcnt!  We require that the `namerd/dtabs` path exists (although it can be empty).  You should create this path as a setup step before running namerd.

**Comment by pvcnt** [comment]
Hi, thanks for your answer! Still, it's strange to get an infinite loop,
instead of an error, isn't it? And it's the same thing if I reference in
linkerd a not-yet created namespace in namerd (with Consul storage), the
namerd's linkerd tab takes forever to load (because of that infinite loop I
guess).

2017-02-27 23:51 GMT+01:00 Alex Leong <notifications@github.com>:

**Comment by adleong** [comment]
We do infinite retries on namerd errors so that if namerd goes down temporarily and then comes back up, linkerd will recover.  In this case, specifically, if you create that path in consul, the next retry will be successful and linkerd will be in a good state.

For the namerd tab in the admin UI, we should probably add a timeout so that the page displays an error instead of hanging forever.  Would you mind filing a separate issue for the admin UI timeout issue?
