### ISSUE TITLE
io.l5d.k8s namer: port should map to service port instead of pod port

### ISSUE THREAD

**Issue by jbachus** [linkerd/linkerd#1143]
When using the io.l5d.k8s namer, routing to `/#/io.l5d.k8s/default/http` (the name of the port in the service) routes to the pods correctly, using their endpoint address as the destination.  However, routing to `/#/io.l5d.k8s/default/80` routes to port 80 of the internal pod IPs.

Example service:
```kubectl describe service sas
Name:            sas
Namespace:        default
Labels:            <none>
Selector:        app=sas
Type:            ClusterIP
IP:            10.100.31.239
Port:            http    80/TCP
Endpoints:        10.102.14.30:3000,10.102.5.39:3000
Session Affinity:    None
```

I would expect that `/#/io.l5d.k8s/default/80` routes to 10.102.14.30:3000 and 10.102.5.39:3000, which is the behavior of the `/#/io.l5d.k8s/default/http` route, however it is routing to 10.102.14.30:80 and 10.102.5.39:80.

We are following the convention of exposing services on port 80, but have not been strict about requiring the port name to match http.  This is the behavior that https://github.com/kubernetes/contrib/tree/master/service-loadbalancer uses.

**Comment by adleong** [comment]
I've started looking into this and it's a bit more challenging than I first anticipated because the service port is not listed in the [endpoints api](https://kubernetes.io/docs/api-reference/v1/definitions/#_v1_endpointport).

In order to do this we'd need to set up a watch on the services api to also maintain a map of port to targetPort for each service.
