### ISSUE TITLE
Why linkerd is written in scala?

### ISSUE THREAD

**Issue by thekalinga** [linkerd/linkerd#1160]
We all know in general, the overall memory requirements of java based solutions are very high.

Given that linkerd is a deamon, why did you chose scala as the language of implementation instead of the same language kubernetes uses, which is go (or) may be some other native compiled languages?

**Comment by olix0r** [comment]
Hi @thekalinga. Thanks for the question.

First of all, we started working on linkerd well before kubernetes 1.0.  linkerd is not and will never be a kubernetes-specific project.  linkerd should work well with kubernetes, but it should also work well in other environments (and should be especially useful in bridging orchestrators).

The primary reason that linkerd was written in scala is because we have extensive production experience with [finagle](https://github.com/twitter/finagle), which is a networking library that we helped develop while operating production services at Twitter.

We chose finagle (and therefore scala), because there is a rich, battle hardened, mega-scale feature set available to us.

That said, we're continually and actively making investments to improve resource utilization.  Watch this space!
