### ISSUE TITLE
dispatcher client stats breaks admin dashboard

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd#1287]
I'm looking at the admin dashboard for the [gob app](https://github.com/linkerd/linkerd-examples/tree/master/gob) running in Kubernetes. When I try to view the "http" router, I see:

![screen shot 2017-05-09 at 4 03 42 pm](https://cloud.githubusercontent.com/assets/9226/25876316/24e309be-34d1-11e7-9163-76be08ef3e79.png)

Here's the metrics payload that produced the error:

[metrics.txt](https://github.com/linkerd/linkerd/files/988248/metrics.txt)

I think the issue is:

```
{
  "rt": {
    "http": {
      "client": {
        "$/inet/127.1/8282": {
          ...
        },
        "dispatcher": {
          "serial": {
            "queue_size": {
              "gauge": 0
            }
          }
        }
      }
    }
  }
}
```

The "dispatcher" key in the "client" map doesn't match the [TRANSFORMER_RE](https://github.com/linkerd/linkerd/blob/master/admin/src/main/resources/io/buoyant/admin/js/src/router_clients.js#L15) that we use to parse client ids in the js code. Maybe we should just skip all client ids that don't match the regex? Or maybe those dispatcher stats aren't scoped properly?

**Comment by esbie** [comment]
I agree that the dispatcher map entry is the problem. Very curious, since our current fixture data has dispatcher as a child of each client (so like under `$/inet/127.1/8282` in this example). I wonder if something has changed recently leaving the dispatcher unscoped.

I'll fix the UI to not error on unexpected client ids and also investigate what's up with the stats scoping.

One thing I noticed is the `metrics.txt` linked has "outgoing" and "incoming" router stats, but there aren't any routers labeled that in the gob example app. @klingerf is that expected or...?

**Comment by klingerf** [comment]
@esbie Good catch -- this is from our k8s test env. Will ping you the link.

**Comment by esbie** [comment]
Update: verified this dispatcher metric appears when the first client is created. Occurs in both netty3 and netty4.

**Comment by adleong** [comment]
I believe this is caused by https://github.com/twitter/finagle/pull/629

**Comment by adleong** [comment]
Blocked on https://github.com/linkerd/linkerd/issues/1595

**Comment by adleong** [comment]
Fixed!
