### ISSUE TITLE
Based on the dcos blue-green deploy

### ISSUE THREAD

**Issue by superwen0001** [linkerd/linkerd#1339]
Using linkerd and namerd 1.0.2 version.
namerd dtab config:

***
/marathonId =>  /#/io.l5d.marathon ;
/svc =>  /$/io.buoyant.http.domainToPathPfx/marathonId ;
/svc/webapp => /$/io.buoyant.http.domainToPathPfx/marathonId/webapp & 5 * /svc/webapp2;

***

Visit namerd admin dtab

[](url)
![47oki3ydximk 5z0s dl r](https://cloud.githubusercontent.com/assets/15228812/26337978/47b82efe-3faf-11e7-84fb-ca88ca5eaa4d.png)

Use http_proxy appear below

![dd rg 9t5xq wfdsq ymqww](https://cloud.githubusercontent.com/assets/15228812/26337991/5f2cb26c-3faf-11e7-8c41-48acabf93419.png)

Have probability to appear

***
No hosts are available for /svc/webapp, Dtab.base=[], Dtab.local=[]. Remote Info: Not Availableroot

***

**Comment by superwen0001** [comment]
I'm not sure whether my writing has a problem, what should be correctly spelled.
English is not very good, please forgive me

**Comment by klingerf** [comment]
Hi @superwen0001 -- this looks basically correct to me. I might suggest the following refactor to your dtab for readability:

```
/marathonId => /#/io.l5d.marathon ;
/srv => /$/io.buoyant.http.domainToPathPfx/marathonId ;
/svc => /srv ;
/svc/webapp => /srv/webapp & 5 * /srv/webapp2;
```

I recommend trying the dtab playground in the _linkerd_ admin UI, instead of the _namerd_ admin UI. That will help you to determine if you've properly configured your linkerd router running on 4140 to properly connect to the namerd namespace that you've configured.

**Comment by adleong** [comment]
Hi @superwen0001, thanks for your interest in linkerd!

I recommend posting on https://discourse.linkerd.io for help with configuring and using linkerd.  Github issues are for bug reports and feature requests.  Thanks!
