### ISSUE TITLE
Linkerd on Mesosphere Enterprise DC/OS strict mode does not work

### ISSUE THREAD

**Issue by daftclouds** [linkerd/linkerd#1445]
Linkerd is available from the DC/OS universe.
In the DC/OS 1.8 release, authorization was introduced in the Enterprise Edition of DC/OS. Marathon only has https available in strict mode so the linkerd fails to deploy as http is only available.

The community version of DC/OS is unaffected by this as strict mode authorization is unavailable.

For linkerd to deploy successfully on an Enterprise DC/OS strict mode cluster the package requires https capabilities

**Comment by ryadav88** [comment]
@siggy ^^

**Comment by siggy** [comment]
Hi @daftclouds. We have instructions for configuring linkerd to connect to an authenticated Marathon in DC/OS Enterprise, have a look at:
https://github.com/dcos/examples/tree/master/linkerd/1.8#mesosphere-enterprise-dcos
https://linkerd.io/config/1.1.0/linkerd/index.html#marathon-authentication

**Comment by ashahan** [comment]
Hi @siggy, on the same team as @daftclouds. Following the documentation you linked, the installation and functionality _do_ work with enterprise DC/OS clusters that are in `permissive` or `disabled` security modes. And in fact you can _install_ linkerd in a `strict` Mesosphere Enterprise DC/OS 1.9 cluster - but linkerd cannot talk to marathon in `strict` mode no matter how I've tried to configure linkerd.

From what I understand about how the linkerd package works with the optional config file (default optional config in the code block at bottom) is that it forces all connections to use `adminrouter` which would be port 443 instead of 80 in a `strict` cluster. So I changed the marathon-port to 443, still linkerd would not work. I attempted to use port 8443 which is the marathon port in `strict` mode, but also that fails. I even tried 8443 with just the `marathon-uri-prefix` of `/` to no avail. The point here is that marathon uses https in `strict` mode but I am not sure if linkerd is set up to work with https in this context.

I looked at all the normal logging locations and potential debugging steps (including the ones in the linkerd UI help page) but was unable to get any information about why the connections were failing with the log level details set to `all`. Any assistance would be useful here - additional logging locations to check, or point me to some other configurations I can test to make this work.

What it looks like when I run linkerd in a `permissive` Enterprise DC/OS Cluster
![linkerdgood](https://user-images.githubusercontent.com/9733477/27613404-f101e5e6-5b60-11e7-8e8a-a5df4c34d6d7.png)

What it looks like when I run linkerd in a `strict` Enterprise DC/OS Cluster with port 8443
![linkerd-bad2](https://user-images.githubusercontent.com/9733477/27613442-26bd783a-5b61-11e7-8aec-d6fbdbda2f17.png)

What it looks like when I run linkerd in a `strict` Enterprise DC/OS Cluster with port 443
![linkerd-bad1](https://user-images.githubusercontent.com/9733477/27613427-10e6582e-5b61-11e7-8067-80846d3cd06d.png)

Default optional config file
```
OPTIONS=$(cat <<EOF
{
  "linkerd": {
    "instances": <node count>,
    "marathon-host": "leader.mesos",
    "marathon-port": 80,
    "marathon-uri-prefix": "/marathon",
    "secret_name": "linkerd-secret"
  }
}
EOF
)
```

**Comment by siggy** [comment]
Thanks this detailed writeup @ashahan. We'll have a look.

**Comment by vadimi** [comment]
We've been experiencing this issue with linkerd and DCOS in strict mode and figured this is happening due to self signed certificates. Linkerd connects to marathon over https, but cannot validate certificates DCOS generates. I even tried curling marathon endpoints from the machine (and container) directly and it fails on ssl verification step. Basically linkerd cannot even perform authentication.

**Comment by wmorgan** [comment]
@vadimi Interesting. Thanks for the pointer. We'll see if we can repro with a self-signed cert.

**Comment by mtweten** [comment]
I was running into this same issue - I was able to make a pretty small change which allows the user to specify TLS config for the marathon namer which allows the namer to hit the TLS protected DC/OS endpoints.

The [change](https://github.com/mtweten/linkerd/commit/9ab96225058caea499cda76a0dd6771f9bf3a593) makes use of the existing TlsClientConfig class, which seems to be a pretty good fit for this use case. The only thing that will go unused in this workflow from that class is the ClientAuth, since strict mode DC/OS doesn't use mutual TLS.

Here's an example configuration:
```
namers:
- kind: io.l5d.marathon
  host: leader.mesos
  port: 443
  prefix: "/io.l5d.marathon"
  uriPrefix: "/marathon"
  tls:
    disableValidation: false
    commonName: master.mesos
    trustCerts:
      - /opt/linkerd/config/dcos-ca.crt
```

where dcos-ca.crt is the self-signed root certificate for the DC/OS CA (as described in [Securing communication with TLS](https://docs.mesosphere.com/1.9/networking/tls-ssl/) and [Downloading the Root Certificate](https://docs.mesosphere.com/1.9/networking/tls-ssl/get-cert/))

If this is an acceptable fix I could go ahead and open a PR for this if you guys want.

**Comment by siggy** [comment]
@mtweten This is awesome! I just confirmed it works on our end. Please create a PR with your change.

A couple comments:
- please update `namerd.md` with the params you just added. you can reference `client_tls.md`, but as you mentioned, indicate that `clientAuth` is unused.
- re-sort the `com.twitter.finagle.buoyant.TlsClientConfig` import line
