### ISSUE TITLE
Correct handling of HTTP responses containing multiple `Content-Length` headers

### ISSUE THREAD

**Issue by hawkw** [linkerd/linkerd#1468]
As seen in https://github.com/linkerd/linkerd/issues/682#issuecomment-312730463. 

It looks like we're mishandling badly-framed HTTP 1.1 responses. According to the spec, proxies are supposed to return 502 errors when the upstream sends a response with multiple conflicting `Content-Length` headers. However, linkerd currently just happily forwards these responses, all headers intact.

**Comment by hawkw** [comment]
While I'd eventually like to look at fixing this behavior downstack from us in Finagle, I think for now the Right Thing to Do is just to add a filter that turns these requests into 502 errors. @olix0r, does that sound good to you?

**Comment by olix0r** [comment]
It's fine to add a linkerd-specific solution for the time being.

You'll likely want to write client and server stack modules that install the appropriate filtering logic to fail requests with multiple content-lengths on the server and fail responses with invalid content-lengths on the client.

The tricky part here is figuring out where to install these filters so that we measure success/failures properly.

**Comment by hawkw** [comment]
Closed by #1475
