### ISSUE TITLE
K8s: Fallback issue if there are no running pods in service

### ISSUE THREAD

**Issue by ievgen-kolomiiets** [linkerd/linkerd#1549]
I have two services in Kubernetes: **service-a** and **service-b**.
Dtab is configured next way:
```
/service => /service-a | /service-b
```
The issue is that if Kubernetes restarts pods in **service-a** and all pods become unavailable traffic doesn’t go to **service-b** anyway.

**Comment by wmorgan** [comment]
@ievgen-kolomiiets thanks for filing this! We'll take a look.

**Comment by hawkw** [comment]
I think before trying to find a fix for this, we'll want to ensure that the issue persists after #1603 is merged. That branch rewrites enough of the Kubernetes namers that it's possible this issue was fixed as well.

**Comment by klingerf** [comment]
Hey @ievgen-kolomiiets, thanks for reporting this, and apologies for the delay in responding.

I tested this a bit, and in my tests linkerd did fallback from `service-a` to `service-b` when all instances of `service-a` disappeared. That said, I think a better way to go about this would be to remove the `service-a` kubernetes service object prior to the deploy, which would force the fallback to `service-b` explicitly. Then you could deploy `service-a` and restore the service object to shift traffic back to `service-a`.

In investigating this, however, I realized that there's currently a bug in linkerd where it does not properly recognize when a service has removed, and it continues to send traffic to instances of the service rather than falling back. I've described this behavior in more detail in #1612, and we're going to work on fixing that as part of the 1.2.0 release.

**Comment by ievgen-kolomiiets** [comment]
Hi @klingerf.
Let me describe my case. `service-a` and `service-b` are services in different availability zones.  
For zone `a` routes look like `/service => /service-a | /service-b` and for `b` - `/service => /service-b | /service-a`. This allows us to avoid cross-zone requests as much as possible.
So if something bad happens in zone `a` and all pods are getting restarted or unavailable I want traffic to go to zone `b`. But what I saw in namerd code that fallback starts working only if there is a `Neg` resolution but instead empty address list is returned for service with no pods.

**Comment by klingerf** [comment]
Great, thanks for the additional info @ievgen-kolomiiets. Your setup makes sense to me, and what you describe is how I expect it to work: the fallback should happen on `Neg`, but won't happen on `Empty`. But as I described in #1612, I think that's not actually how it works at present, and the behavior changed recently. Which version of linkerd are you running? We might actually want to fallback on `Empty` as well, but I think the fact that Linkerd behaves that way now was not a conscientious decision.

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd/pull/1622
