### ISSUE TITLE
Namerd cache the DNS for extensive of time 

### ISSUE THREAD

**Issue by leozc** [linkerd/linkerd#1666]
Background:
We use Linkerd to route traffic between services, the downstream address (for now) is a DNS CNAME to ELB of the service, and we've found the DNS contained stalling IP - or saying DNS resolution contain dead ip addresses.

Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:
AWS ELB DNS maps to a set ELB instances - each instance has an IP as expected.
Usually, each availability zone has one or more ELB instances.

You can do this to find out
`dig myelbdns`  

ELB instance can be scaled up and down and hence a ELB DNS can be solved to different IPs.

Observation:
Namerd remembers some old IPs instead of all the updated ones after the ELB DNS is updated.

Rekick Namerd and the issues resolved

**What you expected to happen**:
Namerd should respect the DNS TTL

**How to reproduce it (as minimally and precisely as possible)**:
 = it is hard/unreliable to repro = 
Setup an ELB and a couple of instances behind this ELB.
We need to force an ELB to scale out - hence it has more instances

* Use traffic to drive the ELB to scale out 
* attach a new instance to a different AZ - so this can force ELB to spin up new instance too.

To observe the change of DNS
 `dig elbname`  meanwhile Check if Namerd can resolve the new IP.

Perform a couple of this auto-scaling iteration and double check if namerd has the consistent entries as DNS.

**Anything else we need to know?**:
We had couple of this inc which re-kicking the namerd help

NOTE: I did manual tests by creating a DNS and update the DNS (with adding/removing/changing IPs), and it seems Namerd successfully picked up the changes.

I have no idea what happened in the ELB context - but I am very sure it is related to stalled IP and the IP was a valid one.

**Environment**:
- linkerd/namerd version, config files: 1.1.2
- Platform, version, and config files (Kubernetes, DC/OS, etc): Linux
- Cloud provider or hardware configuration: AWS
 

My question:
What is the EXACT behavior of DNS resolving, I assume it is Namerd performs the DNS resolving.
and
Who decides which dst ip to be picked for a request  - I assume namerd returns a list of IP and L5d uses whatever LB algorithm to pick the exact dst.

**Comment by klingerf** [comment]
Hey @leozc -- thanks for reporting. This sounds like an issue with caching the DNS resolution for the CNAME for too long. Linkerd uses finagle, which I believe uses the default JVM implementation, to resolve CNAMEs. We'll need to investigate where the bad caching behavior might be coming from.

I'm not too familiar with ELB, but is there any chance it publishes SRV records? We just added [the `io.l5d.dnssrv` namer](https://linkerd.io/config/1.3.0/linkerd/index.html#dns-srv-records), which will do service discovery on a SRV record, and load balance against all IPs contained in the record. That actually sounds more appropriate for your use case. Otherwise, with CNAMEs, I think linkerd just picks the first IP based on the default DNS implementation, and uses that permanently. There isn't any load balancing for CNAMEs that resolve to more than one IP. If it's at all possible to switch to SRV, you might want to try using that instead.

**Comment by leozc** [comment]
Thanks heaps for the quick response - I will work on that tomorrow

**Comment by leozc** [comment]
Another incident -> 1 of the 3 Namerd instances didn't pick up the change.

The step as follow:

foo.bar is alias of elb.bar
and we update the foo.bar points to alias of elb2.bar 

1 of the 3 namerd box didn't pick up the change.
