### ISSUE TITLE
Identify if the local namespace of the calling app can be assumed when l5d searches for the target app name, if namespace is not defined

### ISSUE THREAD

**Issue by zillani** [linkerd/linkerd#1712]
#### Issue Type:

- Feature request

Here's the scenario, 

- I have an app, **app1** in namespace **ns1** &
- **app2** in namespace **ns1** and **ns2**
- linkerd in namespace **linkerd**

When **app1** makes call to **app2** without defining namespace  _(i.e; http_proxy=$L5D:4140 curl http://app2 instead of http_proxy=$L5D:4140 curl http://app2.ns1)_ then, can l5d identify the namespace of **app1** & route to **app2** in **ns1** (preferring the local namespace)

In this case for testing I am requesting from container inside **app1** and doing a proxy curl to **app2**

`http_proxy=$L5D_URL:4140 curl -v http://app2`

this searches for **app2** in **default** namespace because of dtab but is there a way to achieve what we are looking for?

**Environment**:
- linkerd: 1.3.1
- Platform: Kubernetes
- Cloud provider: AWS

**Comment by franziskagoltz** [comment]
Thanks for filing this feature request @zillani!

**Comment by adleong** [comment]
Hi @zillani 
Unfortunately, due to the way that Linkerds are deployed per-host and shared between apps from potentially many namespaces, there isn't an easy way to route based on the originating namespace.

There are a couple of potential workarounds:
* Deploy a Linkerd per namespace, each listening on distinct ports.  Apps in namespace A would be configured to use the Linkerd port for namespace A.  That Linkerd would be configured to route to namespace A.
* Have apps pass a dtab override header that indicates which namespace to route to.

**Comment by zillani** [comment]
ok, got it. What is recommended b/w
- single linkerd daemonset with multi-router configuration? 
(https://discourse.linkerd.io/t/no-hosts-available-error-with-multi-router-configuration/433)
- multiple linkerd daemonset as you suggested?

**Comment by adleong** [comment]
@zillani sorry for the extremely late response.  I would recommend starting with a multi-router configuration.
