### ISSUE TITLE
Feature request: Please add config validation command line function 

### ISSUE THREAD

**Issue by peterfroehlich** [linkerd/linkerd#1796]
It would be really helpful to have a way for linkerd to validate its configuration without spinning up the loadbalancer. 

That means: Validate presence of config files, validate config, validate presence of certs or other included files, report and exit (with fitting return code). This would be immensely useful for most automated (non-containerised) deployments. 

HAproxy, nginx, apache, etc all have a command line parameter to enable this. 

Thanks!

**Comment by deebo91** [comment]
@peterfroehlich, this sounds like a good feature request! Thanks for bringing this to our attention. We will scope out and evaluate what is required.

**Comment by adleong** [comment]
Better config validation is always a good idea!

Linkerd will already exit immediately if the config file is absent or fails to parse.  There are a few things I can see where we can improve:

* For client tls trustCerts we could use the `File` config type instead of string which will validate that the file exists
* Ditto for server tls `certPath`, `keyPath`, `caCertPath`

Are there other validations that you had in mind?  Are you interested in submitting a PR for this?

**Comment by LukaszMarchewka** [comment]
I think an optional parameter "-validate" can solve the request. When the flag is set then Linkerd will exit immediately after loading a config with a proper status and a message.

I can implement it, if you agree.

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd/pull/1854
