### ISSUE TITLE
Retry POST requests 

### ISSUE THREAD

**Issue by ewilde** [linkerd/linkerd#2035]
## Summary 
Allow post requests to be retried on timeout and failure in a similar way to the [existing functionality](https://linkerd.io/config/1.4.2/linkerd/index.html#retryable-idempotent-5xx) for a `PUT` request.

## Context
We make `POST` requests to 3rd party APIs. Sometimes they timeout 😢 . We would like these to be retried as per the [retry configuration](https://linkerd.io/config/1.4.2/linkerd/index.html#retries)

## Possible Implementation
Add a new [response classifier](https://linkerd.io/config/1.4.2/linkerd/index.html#http-response-classifiers) `io.l5d.http.retryableWrite5XX`

### Retryable Write 5XX
kind: io.l5d.http.retryableWrite5XX
kind: io.l5d.h2.retryableWrite5XX

Like io.l5d.http. retryableIdempotent5XX/io.l5d.h2. retryableIdempotent5XX, but `POST` requests may also be retried.

**Comment by adleong** [comment]
Thanks for filing this @ewilde!

I think it would be great to have a response classifier that allows retrying of POSTs.  However, since POST requests may contain bodies, it may be necessary for Linkerd to buffer the bodies in order to be able to retry them.  Furthermore, we would only want to do this for sufficiently small bodies.

See [ClassifiedRetryFilter](https://github.com/linkerd/linkerd/blob/master/router/h2/src/main/scala/io/buoyant/router/h2/ClassifiedRetryFilter.scala#L14) to see how we do this in H2.
