### ISSUE TITLE
io.l5d.localhost transformer fails in linker-to-linker mode.

### ISSUE THREAD

**Issue by fixed-point** [linkerd/linkerd#2086]
# Thanks for your help improving the project! #

## Getting Help ##

Github issues are for bug reports and feature requests. For questions about
Linkerd, how to use it, or debugging assistance, start by
[asking a question in the forums](https://discourse.linkerd.io/) or join us on
[Slack](https://slack.linkerd.io/).

Full details at [CONTRIBUTING.md](https://github.com/linkerd/linkerd/blob/master/CONTRIBUTING.md).

## Filing a Linkerd issue ##

Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:

Requests to linker for a service fail randomly (~30% of the time, roughly) in linker-to-linker mode, despite all instances of the service being available (and responding to requests when hit directly). 

What seems to be occurring is that linker is incorrectly deciding that a resolution for a service instance on the same host as its local linker is not valid for /%/io.l5d.localhost/

The accompanying error is (replacing actual hosts with HOST_ONE, HOST_TWO):

```
Unable to route request!

service name: /svc/cluster/alerts
resolutions considered:
  /%/io.l5d.localhost/$/inet/HOST_ONE/29999 (pending)
  /%/io.l5d.localhost/$/inet/HOST_TWO/29999 (neg)
dtab:
  /svc/cluster => /$/inet/HOST_ONE/29999 & /$/inet/HOST_TWO/29999
  /svc/cluster-metrics => /$/inet/HOST_ONE/29999 & /$/inet/HOST_TWO/29999
base dtab:

override dtab:

```

**What you expected to happen**:

Linker should correctly detect that the service instance is running on the same host, and resolve.

**How to reproduce it (as minimally and precisely as possible)**:

We reproduce consistently with a dtab of the form above (a service routes to two hosts), with both running a local linker in linker-to-linker mode. 

**Anything else we need to know?**:

The issue disappears (and all requests succeed as expected) when running in linker-to-service mode instead of linker-to-linker, with no changes to the dtabs/service instances.

If I start a linker instance in linker-to-service mode using the same namerd as the existing instances, the new instance will succeed in routing requests (and the other two will continue failing 30% of the time).

**Environment**:
- linkerd/namerd version, config files: Linker and Namer both running 1.4.5. 

Config file for linker: [here](https://gist.github.com/fixed-point/51f4a86ce767f13260c780b3096c8821)

- Platform, version, and config files (Kubernetes, DC/OS, etc): N/A, we run linker-to-linker bare-metal without k8s/DCOS/etc.
- Cloud provider or hardware configuration: Two linux servers on the same local network.

**Comment by adleong** [comment]
Hi @fixed-point!  This is a good question.  What's going on is an interaction between dtab unions (the & operator) and Linker-to-Linker mode.

When the first Linkerd (outgoing) routes the request, it randomly picks one of the union arms to use: HOST_ONE or HOST_TWO, and sends the request to the Linkerd running on the node of that instance.  When the second Linkerd (incoming) gets that request, it again randomly picks one of the union arms to use and attempts to send the request an instance running on that node.  However, if the two Linkerds made different random choices, there may not be an instance running on the node for the second Linkerd to route to.

This can be resolved by changing the incoming configuring to use the choice made by the outgoing Linkerd instead of re-evaluating the dtab itself.  

```
  identifier:
    kind: io.l5d.header
    header: l5d-dst-client
  dtab: /svc/%/io.l5d.daemonset/*/*/* => /
```

This causes Linkerd to read the `l5d-dst-client` header, strip off the transformer prefix, and then send the request to that destination (the destination picked by the outgoing router).

Hope that helps!

**Comment by adleong** [comment]
Yes, the `io.l5d.header.path` identifier for H2: https://linkerd.io/config/head/linkerd/index.html#http-2-header-path-identifier

**Comment by fixed-point** [comment]
I can confirm this resolves the issue. Thank you very much!
