### ISSUE TITLE
Can't find documentation

### ISSUE THREAD

**Issue by mjschmidt** [linkerd/linkerd#2094]
I am having trouble getting my applications to send their http traffic to linkerd and the documentation (from what I can see) as for how to do this isn't very descriptive. I am assuming my application does not have an http_proxy variable because that did not work. I am trying to just use a plain nginx for the time being to get an example of how we would migrate our current applications to use this service mesh. 

Docs I was looking at:
https://linkerd.io/1/getting-started/k8s/

I have a few questions:
1) What does this mean:
"you must configure your application to send traffic directly to Linkerd" does that mean I can't use vanilla kubernetes files like this one here without making container changes?
https://github.com/kubernetes/contrib/blob/master/statefulsets/zookeeper/zookeeper.yaml

2) I am not really sure what the Host/authority label is. Is there more documentation on that?

I look forward to using linkerd! I did have to change loadbalencer to nodeport to get the service external ip to not show up as forever pending, but that yaml was super convenient

**Comment by dadjeibaah** [comment]
@mjschmidt we have a few places where you can find helpful documentation on how to get started with Linkerd in k8s. I highly recommend going the blog series [A Service Mesh for Kubernetes](https://blog.buoyant.io/2016/10/04/a-service-mesh-for-kubernetes-part-i-top-line-service-metrics/). The blog series has detailed instructions on how to use the different features Linkerd provides in Kubernetes. 

Another great resource is the [linkerd k8s examples repo](https://github.com/linkerd/linkerd-examples/tree/master/k8s-daemonset) which contains a variety of YAML configurations you can use to set up Linkerd in k8s.

To answer your questions:
1. You can set up your application to send traffic through Linkerd by setting an `http_proxy` environment variable for your containers in you `application.yaml`. [Here](https://github.com/linkerd/linkerd-examples/blob/master/k8s-daemonset/k8s/hello-world.yml#L28) is an example of how to do that. This allows you not to have to change your application code to send traffic to Linkerd.

2. The host/authority label is an HTTP header set to the value immediately after the `http://` protocol section of a URL. HTTP/2, uses an `:authority` header instead of `Host`. The `:authority` header is set to the hostname of an HTTP/2 server. 

Linkerd's default identification behavior is to read the `Host` or `:authority` header of either HTTP/1.1 and HTTP/2  requests to figure out what service names it will use to route incoming requests to their destination servers.
There is documentation that dives deeper into how Linkerd routes requests [here](https://linkerd.io/1/advanced/routing/)

**Comment by mjschmidt** [comment]
Thanks will take a look!
