### ISSUE TITLE
Improve Prometheus time series names for exception counters

### ISSUE THREAD

**Issue by zackangelo** [linkerd/linkerd#2118]
Prometheus metric names for exception counters have the exception in the name (e.g., `rt:server:exn:io_netty_handler_codec_DecoderException`). This makes it difficult to aggregate or display by exception because it requires you to know in advance all of the possible exceptions. 

Perhaps a better way would be to consolidate all exceptions into a single counter and put the exception name in a label (e.g. `rt:server:exceptions{exception="io_netty_handler_codec_DecoderException"}`). That way, the exception names could be grouped or regex matched and you can select all of them using the same time series.

**Comment by wmorgan** [comment]
Thanks @zackangelo!

**Comment by dadjeibaah** [comment]
@zackangelo, @kleimkuhler and I are working on this issue and we have some quick questions. Do you mind sharing the scenario in which Linkerd's prometheus endpoint records `rt:server:exn:io_netty_handler_codec_DecoderException`? Is this caused by invalid HTTP/HTTP2 request reaching Linkerd on the server-side? We tried sending an HTTP request to LInkerd with a malformed HTTP request but didn't get any `exn` lines. We did, however, get Linkerd to display exceptions returned by a downstream service and have that show up as `failures` in the Prometheus endpoint.
