### ISSUE TITLE
Namerd returning empty dtab after consul failure

### ISSUE THREAD

**Issue by hsmade** [linkerd/linkerd#2145]
# Thanks for your help improving the project! #

## Getting Help ##

Github issues are for bug reports and feature requests. For questions about
Linkerd, how to use it, or debugging assistance, start by
[asking a question in the forums](https://discourse.linkerd.io/) or join us on
[Slack](https://slack.linkerd.io/).

Full details at [CONTRIBUTING.md](https://github.com/linkerd/linkerd/blob/master/CONTRIBUTING.md).

## Filing a Linkerd issue ##

Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:
The consul cluster became unresponsive. Namerd noticed and emptied the dtab for every service. This then ended up on Linkerd, causing it to not be able to route requests.

**What you expected to happen**:
I would expect that when Namerd identifies that Consul is not responding, it will retain the known-good state of services.

**How to reproduce it (as minimally and precisely as possible)**:
Block traffic between consul and namerd.

**Anything else we need to know?**:

**Environment**:
Linkerd config:

    - protocol: thrift
      label: port-10000
      thriftProtocol: binary
      interpreter:
        kind: io.l5d.namerd
        dst: /$/inet/namerd.service.consul/4100
        namespace: 10000
      servers:
      ......
      client:
       .....

Namerd config:

        interfaces:
        - kind: io.l5d.thriftNameInterpreter
          port: 4100
          ip: 0.0.0.0
        - kind: io.l5d.httpController
          port: 4321

        namers:
        - kind: io.l5d.consul
          host: 127.0.0.1
          port: 8500
          includeTag: false
          useHealthCheck: true
          healthStatuses:
          - passing
          consistencyMode: stale

        storage:
          kind: io.l5d.inMemory
          namespaces:
              port-10000: /svc => /#/io.l5d.consul/dc/my_service

Linkerd / Namerd version: 1.4.6

Namerd log:

    W 1008 13:54:35.666 UTC THREAD23 TraceId:9220a1acd06f2ba0: consul datacenter 'dc' service 'my_service' observation error UnexpectedResponse(500: rpc error: EOF). Last known state is 
    Bound(Set(Inet(/x.x.x.x:yyyyy,Map(endpoint_addr_weight -> 1.0)), 
    Inet(/x.x.x.x:yyyyy,Map(endpoint_addr_weight -> 1.0)), 
    Inet(/x.x.x.x:yyyyy,Map(endpoint_addr_weight -> 1.0))),Map())

Linkerd log:

    I 1008 13:54:43.618 UTC THREAD86 TraceId:cd339c016207d896: #/io.l5d.consul/dc/my_service: name resolution is negative (local dtab: Dtab())

**Comment by adleong** [comment]
Thanks for reporting this @hsmade.  This is definitely not the intended behavior, Linkerd should continue to use the last known dtab if it cannot reach Namerd.  We will try to reproduce what you have described.

Just so that we can follow your reproduction as accurately as possible, how did you block traffic between Linkerd and Namerd?  Firewall?  Kill the Namerd process?  Chop the cat5 cable with an axe?

**Comment by hsmade** [comment]
I like the axe idea :) The issue we actually had was that the consul server got overloaded, so connections started to time out and drop. I guess you could simulate that by ddossing consul.

**Comment by adleong** [comment]
It looks like this is probably a consequence of this change: https://github.com/linkerd/linkerd/pull/1863

The problem is that Consul overloads the semantics of a 500 response.  It could mean that the DC that we supplied does not exist, in which case we wish to return Neg.  Or it could also mean that there was some internal error in consul, in which case we would want to continue to use the previously known resolution.  It doesn't seem like there's a nice way to differentiate between these two states other that checking the human readable error in the response, which feels somewhat brittle to me.

@dadjeibaah do you have any ideas here?

**Comment by dadjeibaah** [comment]
Yea this is tricky. I also do not like the idea of checking the human-readable error from the 500 response and using that info to determine what state the namer should be in. I am in favor of reverting this change back so that all 500 responses always use the last known good state and always retry.  

#1863 was meant to fix a case where nonexistent dcs would never resolve the namer state. It feels as if that is an edge case scenario and that more often than not a dc should always exist.

**Comment by hsmade** [comment]
I think the answer may lie in the difference of state in time. If your DC
doesn't exist, you'll find that out on the first call. A DC doesn't usually
cease to exist during runtime. Where as the other reasons for 500 will.

**Comment by adleong** [comment]
This is related to https://github.com/hashicorp/consul/issues/4901
