### ISSUE TITLE
Add support for rate limiting

### ISSUE THREAD

**Issue by robertpanzer** [linkerd/linkerd#2159]
Issue Type:

- [ ] Bug report
- [X] Feature request

It would be nice if Linkerd could add support for rate limiting:

- Rate limits should be specific to a client name.
- Rate limits should be obtained from a plugin.
- The plugin should return an Activity so that rate limits can be updated at runtime.
- In case the rate limit is reached Linkerd should by default return HTTP 429 stating the period after that new requests can be sent.
  It would be nice though if the plugin would be able to create a custom response.
- Exceeded rate limits should be reported via the stats.

**Comment by robertpanzer** [comment]
Hi @adleong 

That's very good questions :)

For our use case the limit can be per instance. 

Regarding server side or client side limits:
Is there a difference if we have a Linkerd instance in front of the service?

**Comment by samek** [comment]
I would definitely have it per service :)

**Comment by adleong** [comment]
Hi @samek!  Per-instance and per-service rate limiting are pretty different in purpose (per-instance limits usually protect the service itself from excess load and allows the limit to scale with the number of instances whereas per-service limits usually protect some shared resources like a database and you don't want the limit to scale with the number of application instances) and in implementation (per-service limits generally need some kind of centralized coordination between instances).  

For the purposes of keeping them separate, let's focus on per-instance limits in this issue.  @samek if you could file another issue where we can discuss per-service limits, that would be great!

**Comment by adleong** [comment]
I think it should be already possible to implement per-instance rate limiting as a request authorizer plugin.  Let me lay out what I mean.

We could create a request authorizer plugin that has the following behavior.  When it receives a request, it increments an in-memory count.  If the count exceeds the limit, the request is rejected.  The count is reset to 0 at a regular period.  Since request authorizers are installed in the endpoint stack, each instance will get an separate independent count.  

* In a daemonset deployment, the plugin should only be installed on the "incoming" routers.   
* The limit could be read from an external service or from config
* the plugin could be selectively installed on certain clients
* the plugin can return a ResponseException which allows it to render a specific response to the caller

The config could look something like this:

```
routers:
- label: incoming
  protocol: http
  [...]
  client:
    kind: io.l5d.static
    configs:
    - prefix: /%/io.l5d.localnode/#/io.l5d.k8s/default/http/serviceA
      requestAuthorizers:
      - kind: io.l5d.rateLimit
        limit: 100
        periodSecs: 15
```

which would configure Linkerd to only allow 100 requests per 15 seconds to each instance of serviceA.

The pseudo-code of the plugin filter would be something like:

```
val limit = // Get from config or external service
val count = new AtomicInteger()

timer.schedule(period) {
  count.set(0)
}

def apply(req: Request, svc: Service[Request, Response]): Future[Request] = {
  if (count.get >= limit) {
    return new ResponseException(/* insert response here */)
  }
  count.increment()
  svc(req)
}
```

@robertpanzer does that match up with what you were thinking?  If so, we can put together a proof-of-concept plugin along these lines.

**Comment by wmorgan** [comment]
@robertpanzer ping! We are planning on taking a stab at this next week.

**Comment by robertpanzer** [comment]
This looks great!

Would it be possible to have the counter per client name?
If I read the code above correctly the counter would limit per prefix?

Also I am wondering if it's already possible to configure requestAuthorizers for the clients, that would be new, right?

**Comment by dadjeibaah** [comment]
Hi @robertpanzer, we think we have a good first POC for rate limiting. The rate limiting functionality has been build as a separate plugin and can be found [here](https://github.com/dadjeibaah/rate-limiter). In order to get this working we had to move the `requestAuthorizers` config section to the client portion of the Linkerd config.

To test it the plugin, checkout the rate limiter plugin code and then build it using sbt like so:
```bash
./sbt rate-limiter:assembly
```

Then, when running Linkerd, you would need to ensure that there is a `plugins` directory alongside Linkerd and that you set an `L5D_HOME` environment variable to point to that plugins directory. The directory should contain a rate-limiter jar that is produced after the command specified above completes.

In your Linkerd config file, you can specify a rate limit for a client like so:
```yaml
...
client:
kind: io.l5d.static
- prefix: /svc/<service_name>
configs:
  rateLimiter: 
    limit: 100
    intervalSecs: 1
```

Finally running everything together would look like this:
```bash
$ cp /path/to/ratelimiter/plugin/target/scala-2.12/rate-limiter-assembly-0.1.0-SNAPSHOT.jar plugins/
$ L5D_HOME=$(pwd) ./linkerd-1.5.1-SNAPSHOT-exec basic.config.yml
```
We would love to hear any feedback you may have and if this fits your use case.

**Comment by robertpanzer** [comment]
Thanks @dadjeibaah
I'll check as soon as possible!

**Comment by robertpanzer** [comment]
I had a look at this plugin and it looks great!

It seems though that clients are allowed twice the limit in the first interval or if the previous interval didn't see any requests.
Do you know the impact of the scheduling of the decrementToZero updater for very high rate limits like 100 requests per second? That would also run the timer every 10 msecs if I'm not wrong.

**Comment by kleimkuhler** [comment]
@robertpanzer Thank you for the review! If you are able to take take a look at [#2](https://github.com/dadjeibaah/rate-limiter/pull/2), you'll find these issues are addressed.

The first window, as well as windows that had no requests sent in the previous window, now reset the request count so that the limit cannot be doubled.

The scheduler has also been removed. It now works with timestamps so that a short period will not lead to any type of performance degradation.

**Comment by kleimkuhler** [comment]
Hi @robertpanzer -I am looping back around to this and I did not address your final bullet point in the original issue report:

> Exceeded rate limits should be reported via the stats.

I'm wondering if you would like the rate limiter example provided to have that functionality added? I realize it has been a few weeks since the last activity on this, but if you would still find that helpful I can work on adding that. Let me know either way, thanks!

**Comment by steve-fraser** [comment]
Hi All, any update on this? Will this be put into Linkerd?

**Comment by cpretzer** [comment]
hi @steve-fraser Linkerd 1 is mostly in maintenance mode while the community focuses on developing features for Linkerd 2.

If you're interested in contributing this feature, we'd love your help with it.
