### ISSUE TITLE
Can i use linkerd to server my static files /or linkerd as the web server

### ISSUE THREAD

**Issue by bansalrajat** [linkerd/linkerd#2161]
# Thanks for your help improving the project! #

## Getting Help ##

Github issues are for bug reports and feature requests. For questions about
Linkerd, how to use it, or debugging assistance, start by
[asking a question in the forums](https://discourse.linkerd.io/) or join us on
[Slack](https://slack.linkerd.io/).

Full details at [CONTRIBUTING.md](https://github.com/linkerd/linkerd/blob/master/CONTRIBUTING.md).

## Filing a Linkerd issue ##

Issue Type:

- [ ] Bug report
- [ ] Feature request

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- linkerd/namerd version, config files:
- Platform, version, and config files (Kubernetes, DC/OS, etc):
- Cloud provider or hardware configuration:

**Comment by dadjeibaah** [comment]
Thanks for opening this issue @bansalrajat. Linkerd is proxy for managing service-to-service communication between microservices and can't serve static files like a web server. Since this issue was more of a question rather than a bug or feature request, I am going to close this issue for now. If you have any more additional questions, please feel free to join our [Linkerd Slack](https://slack.linkerd.io/) where you will find a friendly Linkerd maintainer ready to answer your questions 😄.
