### ISSUE TITLE
Namerd connection leak to kubernetes

### ISSUE THREAD

**Issue by chrisgoffinet** [linkerd/linkerd#2251]
Working on a repo test case but wanted to get this out as it's pretty serious. We've been observing a case where namerd is creating connections to the kubectl proxy that slowly leak over time. The way we detected this was by looking at how long it was taking to start watches against the endpoints API. 

We have a cronjob that updates the dtabs against namerd every 5 minutes. After a period of time we started noticing the k8s client latency grow to minutes. After further inspection, we've found a bug in Kubernetes that was just recently fixed yesterday in how `kubectl proxy` handles http2 connections and max concurrent streams.

Kubernetes has vendored the golang http2 library, where the default behavior is to not open a new connection once it reaches the maxConcurrentStreams (this value is 250). Because kube-apiserver uses this http2 package, the server would communicate back to http2 client (kubectl proxy), so once you have 250 watches running, you will block until there is a slot available. This behavior was causing the k8s client latency to be high because services trying to be watched via Namerd would block and thus miss updates, etc. The correct behavior should be to open a new connection once the max streams is hit.

We do have a test case to show this behavior (we will share), and we have tested out a new kubectl build where Kubernetes team updated their dependencies to the changes in go 1.12. It's not enough to just compile Kubernetes with a newer version of go, that's why it was important for them to update.

https://github.com/golang/go/issues/27044
https://github.com/kubernetes/kubernetes/pull/75289

**Comment by chrisgoffinet** [comment]
Here is the test case for the kubectl proxy issue.

[proxy-streams.zip](https://github.com/linkerd/linkerd/files/2968709/proxy-streams.zip)

**Comment by thedebugger** [comment]
Here is the snapshot of namerd metrics for k8s namer client. It has connections, request metrics, and latency 
![image](https://user-images.githubusercontent.com/1693823/54396305-c01dbf80-466f-11e9-83d7-9458ba11714c.png)

**Comment by adleong** [comment]
This is fascinating, thanks @chrisgoffinet and @thedebugger!  Very nice find.

If I understand the implication, `kubectl proxy` is automatically upgrading the HTTP/1.1 requests from Linkerd to HTTP/2 requests to the kubernetes api server.  Is that correct?

It seems like two potential solutions could be:
a) Build kubectl from master as you describe above.
b) Change the k8s namer to send HTTP/2 requests instead of HTTP/1.1 requests so that we can do our own stream management.

Do those solutions make sense to you?  Do you have a feeling about which would be better to pursue?

**Comment by chrisgoffinet** [comment]
@adleong I think using http2 and doing our own stream management is the right approach. Relying on http1/.1 upgrading and version of kubectl can be problematic as you can see. What happens if Go makes further changes?

**Comment by adleong** [comment]
Another potential solution is to simply increase the value of maxConcurrentStreams on the Kubernetes api server (which I believe can be set by a flag).  If Linkerd needs to watch more than 250 services, I think it would be better to raise this limit and have all of those watches on a single connection, rather than splitting them across multiple connections.

**Comment by chrisgoffinet** [comment]
Not a solution. Cloud providers like GKE and AWS Don't allow you to make
these configurations

**Comment by adleong** [comment]
@chrisgoffinet switching to using http2 and our own stream management would require implementing something like https://github.com/linkerd/linkerd/issues/2253 which would be non-trivial.  I think we should explore using a recent kubectl build before resorting to that.

**Comment by adleong** [comment]
@chrisgoffinet thoughts on the above?

**Comment by thedebugger** [comment]
@adleong we did go back to kubectl 1.7.1 that does solve the go bug. It provides us with more runway - kubectl is creating new connections when max_stream limit is reached but it doesn't solve the underlying connection leak that namerd has which causes the problem at the first place. Since there is a leak, we would see another failure e.g. fd limit. 

Here is the snapshot of namerd connections to kubectl. As you can see, connections are growing over time. NOTE, the drops are namerd restarts.

<img width="2540" alt="Screen Shot 2019-04-04 at 11 17 37 AM" src="https://user-images.githubusercontent.com/1693823/55578856-c382f480-56cb-11e9-9bcd-6b98d14d7969.png">

**Comment by adleong** [comment]
do you know what watches Namerd has on the kubernetes API?  Upgrading kubectl proxy lifts the 250 service limit, but you could still run into issues if Namerd is attempting to watch a very high number of services.  Have you looked at the io.l5d.k8s namer state in Namerd?

**Comment by dadjeibaah** [comment]
@chrisgoffinet @thedebugger, we've updated the Linkerd's kubectl sidecar docker image to use the latest kubectl which is `v1.14.3`. You are now able to update the kubectl container image like so:

```yaml
- name: kubectl
        image: buoyantio/kubectl:v1.14.3
        args:
        - "proxy"
        - "-p"
        - "8001"
```

Let me know if this fixes this issue so we can go ahead and close it. Thanks!

**Comment by chrisgoffinet** [comment]
I have confirmed this works

**Comment by dadjeibaah** [comment]
Awesome! I am going to go ahead and close the issue then, thanks @chrisgoffinet!
