### ISSUE TITLE
Validate suggested http2 headers on server in gRPC runtime

### ISSUE THREAD

**Issue by koiuo** [linkerd/linkerd#2326]
Issue Type:

- [ ] Bug report
- [x] Feature request

**What happened**:
Current gRPC runtime implementation by Buoyant doesn't validate `content-type` header in incoming requests.

A generic http2/gRPC client making a request to any gRPC endpoints exposed by linkerd/namerd will fail to interpret the response and the error will not tell, what's wrong.

To avoid such issues gRPC over HTTP2 spec suggests setting (on client) and validating (on server) following headers
* Service-Name → ?( {proto package name} "." ) {service name}
* Message-Type → {fully qualified proto message name}
* Content-Type → "application/grpc+proto"

Content-Type validation is the most desirable one (and it's also the easiest to implement).

**What you expected to happen**:

Server should return corresponding status codes if values of the headers do not match expected values.

**How to reproduce it (as minimally and precisely as possible)**:
Assuming a gRPC endpoint (for example mesh interface) is exposed on port 4101:

```
[~]$ curl -v --http2-prior-knowledge localhost:4101                                                                                                                         

*   Trying ::1:4101...
* TCP_NODELAY set
* Connected to localhost (::1) port 4101 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5650af9c2f30)
> GET / HTTP/2
> Host: localhost:4101
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 1000)!
* REFUSED_STREAM, retrying a fresh connect
* Connection died, retrying a fresh connect
* Closing connection 0
* Issue another request to this URL: 'http://localhost:4101/localhost:4101'
* Hostname localhost was found in DNS cache
*   Trying ::1:4101...
* TCP_NODELAY set
* Connected to localhost (::1) port 4101 (#1)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5650af9c2f30)
> GET /localhost:4101 HTTP/2
> Host: localhost:4101
> User-Agent: curl/7.65.3
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 1000)!
< HTTP/2 400 
< te: trailers
< via: h2 linkerd
< 

* Connection #1 to host localhost left intact
```

**Environment**:
- linkerd/namerd version: 1.7.0

This is related to https://github.com/linkerd/linkerd/pull/2324

**Comment by adleong** [comment]
Hey @edio!  Linkerd's data path doesn't use the gRPC runtime, it simply treats the traffic as H2 and proxies it to the destination.  I think in this case, it's the responsibility of the destination server to validate the request headers and send the appropriate response headers.  Linkerd will simply proxy these through.

The gRPC runtime is used when Linkerd itself needs to do gRPC communication, such as when it communicates with Namerd.

**Comment by edio** [comment]
@adleong, thanks for clarification. I do understand this, and in this ticket I had in mind exactly the endpoints exposed by linkerd/namerd, like mesh interface.

Unlike the issue fixed in #2324 this one isn't a blocker (at least at the moment). I personally consider it mostly a cosmetic issue.
1) having this validation makes buoyant's gRPC runtime closer to the spec
2) in the example above when I do a request with curl to a port with mesh interface is exposed, from a correct gRPC implementation I'd expect something like `415: Unsupported Media Type` instead of request just hanging
3) if invalid grpc request is made, by setting and validating all headers we'll perhaps be able to emit a nice human-readable error

To be fully frank, I created this issue because it was requested during PR review :sweat_smile: . Whether mostly cosmetic benefits justify the effort and potential perfomance cost is up to you, I wouldn't push for this issue.

**Comment by adleong** [comment]
Cool, thanks for the clarification!

**Comment by edio** [comment]
Let me also explain why I didn't introduce this change in the PR.

1) At NCBI we often upgrade linkerd and named independently. If we introduce both the headers and their validation in the same release, independent upgrades won't be possible.
2) At NCBI we have custom apps that talk to Namerd using interpreter-mesh. Again, introducing validation abruptly would force us to release new versions of our apps that talk to namerd and deploying them simultaneously with linkerd upgrade.

That's why even if we are to implement this, we shouldn't haste and perhaps should start with emitting a warning if headers are not valid. Full validation should be released at least in the release coming next after introducing headers.
