### ISSUE TITLE
Make linkerd stats compatible with InfluxDB LINE

### ISSUE THREAD

**Issue by stevej** [linkerd/linkerd#474]
(this is a request from the customer survey)

https://docs.influxdata.com/influxdb/v0.13/write_protocols/line/#main-nav

We can start with the prometheus stats rewriter.

**Comment by olix0r** [comment]
Sounds like a good target for the telemeter plugin system.

**Comment by wei-hai** [comment]
+1

**Comment by halve** [comment]
Hello Buoyant. We have a strong need for a LINE protocol telemeter. Prometheus is not in the picture yet.

The Grafana dashboard in linkerd-viz are very compelling, but we cannot simply dump /admin/metrics/prometheus metrics into Influx using Telegraf's Prometheus plugin. The data has to be transformed carefully so that we can use InfluxQL's math functions. By default, the plugin will create a separate measurement for each metric (think table).

In InfluxDB 0.9+, JOINs are not possible: https://docs.influxdata.com/influxdb/v0.9/concepts/08_vs_09/#joins - "In InfluxDB 0.9 neither the MERGE nor JOIN operations are supported."

Consequently, to pull off the slick success graphs in linkerd-viz, it seems the success and request counter must be 'fields' of the same measurement. Then we could get the best analog to the PromQL query used to power the panel in linerd-viz: `irate(rt:dst_id:success{rt="$router",service=~"$service",instance=~"$instance"}[1m]) / irate(rt:dst_id:requests{rt="$router", service=~"$service",instance=~"$instance"}[1m])`

This would translate to something *like*

SELECT irate(success) / irate(request) FROM "rt:dst_id"

Notice that this query is only reference one measurement"

**Comment by siggy** [comment]
@halve, et al, here's a proposal for what an influxdb LINE telemeter output would look like:
https://gist.github.com/siggy/1fa809ec5f3f2bd23be81665d5d5d788

Feedback welcome. We have this working internally, and would appreciate some folks trying it out prior to release. Code is available at https://github.com/linkerd/linkerd/tree/siggy/influxdb.

a few notes:
- very similar to the prometheus telemeter, but with each metric turned into a field and moved up into its parent as a measurement
- the telemeter data would be available on `/admin/metrics/influxdb`
- each measurement includes a `host` tag, set from the `Host` header in the collector's request
- a few example queries:
  - success rate for each app: `SELECT DERIVATIVE("success", 1s) / DERIVATIVE("requests", 1s) FROM "rt:dst_id" GROUP BY "dst_id"`
  - success rate for each linkerd instance: `SELECT DERIVATIVE("success", 1s) / DERIVATIVE("requests", 1s) FROM "rt:srv" GROUP BY "host"`
- until telegraf adds a LINE protocol input plugin, best practice will be to use the `exec` plugin with curl commands. example `telegraf.conf`:

```
[[inputs.exec]]
  # the first command demonstrates using the default host header, yielding a "host=192.168.1.129:9990" tag
  # the second command demonstrates setting a custom host header, yielding a "host=custom_host" tag
  commands = [
    "curl -s http://192.168.1.129:9990/admin/metrics/influxdb",
    "curl -H 'Host: custom_host' -s http://192.168.1.129:9990/admin/metrics/influxdb",
  ]
  data_format = "influx"
  timeout = "5s"

  # further examples of custom measurement and tag names
  name_prefix = "l5d:"
  [inputs.exec.tags]
    l5d_tag1 = "foo"
    l5d_tag2 = "bar"

[[outputs.influxdb]]
  urls = ["http://127.0.0.1:8086"]
  database = "l5d"
```
