### ISSUE TITLE
Need better support for writing plugins

### ISSUE THREAD

**Issue by jduan** [linkerd/linkerd#718]
I had a chat with Oliver on Slack today regarding this.

Right now, linkerd has limited support for users to write plugins. What's needed are:
- a new plugin system that can install user plugins (the goal is not to be able to support arbitrary filters)
- users can write plugins such as filters
- modular subsystems for big things like “rate limiting"

**Comment by olix0r** [comment]
thanks for opening this, @jduan.  Let me clarify a few points related to this:

User-provided plugins are already supported.  when the L5D_HOME environment variable is set, linkerd will automatically add $L5D_HOME/plugins/*.jar to its classpath.  linkerd's plugin subsystem will automatically load these plugins before processing configuration, so that plugins may be configured via the config file.

We currently do not plan to introduce a "generic filter plugin" interface.  Instead, we'd prefer to carve out specific interfaces for each functional thing that plugins _do_ (for instance, rate limiting).  If linkerd doesn't currently expose an interface for this, we should add a plugin system (and we'd probably want to start with enumerating each subsystem in its own Issue).

We may consider loosening these constraints if we encounter a number of filter types that really are unique to one deployment, but I'd rather be forced into that decision than to start with an overly generic interface.

**Comment by rsimonfitbit** [comment]
Thanks. Let me give a little more background on what we are trying to accomplish with linkerd.

We have several Finagle-based services up and running. These are mostly Java. We are making use of Finagle's extensibility to add in some of our own functionality. One example is a rate limiting filter. This filter will extract the client ID from the request then check with a rate limiting service to see if the client is over the limit across all instances of the service it is trying to talk to. Currently rate limits are applied per service but we can imagine supporting per service method rate limits in the future.

Another filter we have is for extracting the service method name being called. Finagle does not provide service method level metrics out of the box. Therefore, we added a filter that extracts the service method name and sticks it in a com.twitter.finagle.context.Contexts object. We can then use the service method name when generating metric labels like requests per second, error rate, etc.

These are just two examples of how we have extended Finagle. There are others built or in the process of being built like custom load balancing algorithms, custom admin pages, authentication filters, custom metrics, etc.

We now need to support some non-JVM services that we have. We'd like them to get all the goodness of Finagle as well as our Finagle extensions. Linkerd certainly seems like an ideal fit for this use case. In fact, in the long term I could imagine only using Linkerd instead of "embedded Finagle".

Probably the most important use case for us to start with is rate limiting support. However, I wanted to provide the additional context because I thought it might be useful for you.

Is this something you are looking to address soon or should we propose some changes?

**Comment by fantayeneh** [comment]
Another use case we are trying to use the plugin system, is for injecting a/b test headers.
Is the plan to extending the plugin system still on?

**Comment by jacktuck** [comment]
@fantayeneh +1.

I was thinking about whether it would be possible to add a caching plugin could help improve latencies and even fault tolerance. Not sure if that's something that would be wanted broadly enough to warrant open a feature request for. Any thoughts on this @olix0r ? :)

**Comment by adleong** [comment]
Closing this in favor of #1006 and #1255
