### ISSUE TITLE
h2 tracing

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd#732]
Not only do we need to ensure parity with http tracing, but we should ensure that we're properly annotating stream frames (i.e. data frames, trailers)

**Comment by klingerf** [comment]
Just wanted to add some of my own notes that will (hopefully) help with implementing and testing this later.

I sent some h2 traces to zipkin. Here's what I noticed:

* All server spans from all requests have the same (default) trace id. This is because we don't have an h2-protocol-specific trace initializer.
* Server and client spans are not connected. Client spans pick up a separate trace ID and appear as a separate trace in the UI. Again, this is related to not having an initializer.
* Client spans don't have an RPC label. This requires calling `Trace.recordRpc` somewhere in the h2 stack, which we're not doing.

For example, after sending 2 requests, I see only 1 server span, with multiple SR/SS annotations:

![screen shot 2017-01-30 at 4 27 49 pm](https://cloud.githubusercontent.com/assets/9226/22447733/15716996-e709-11e6-8a4c-574d029898cb.png)

And then I see two separate traces with the client spans. Both look like this:

![screen shot 2017-01-30 at 4 28 43 pm](https://cloud.githubusercontent.com/assets/9226/22447749/32a6c70e-e709-11e6-803e-fc08a4547558.png)
