### ISSUE TITLE
Should each path stack have its own retry budget?

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd#737]
Currently, all path stacks on the same router share a retry budget.  This means that one misbehaving downstream can (by returning many retryable errors) consume the entire budget, leaving no budget for requests to other downstream services.

Could this be solved by having each path stack have its own separate retry budget?

**Comment by OleksandrBerezianskyi** [comment]
In our topology linkerd talks to many different endpoints managed by different team and all of those have different performance/load requirements. Having that said it would be very good to expose every single config from: https://twitter.github.io/finagle/guide/Clients.html for each path stack. There should be a default config that is used if a particular config is missing. 

Also please note that because linkerd config and a particular service has different lifecycles we want to reload or at least add particular client config dynamically, and preferably via API and watched persistence (the same way as namerd works).

**Comment by adleong** [comment]
This is now the case.  Each path stack has its own individual retry budget.
