### ISSUE TITLE
Better documentation and error messages when namerd io.l5d.thriftNameInterpreter misconfigured

### ISSUE THREAD

**Issue by brendanyounger** [linkerd/linkerd#825]
I ran into these issues setting up a simple linkerd + namerd configuration.

I made the mistake of omitting the `io.l5d.thriftNameInterpreter` interpreter from namerd's config.yml file.  In the linkerd config.yml, I created a `io.l5d.namerd` interpreter which pointed to the namerd `io.l5d.httpController` port.

This is what I observed:

* linkerd would not resolve anything.  The only error was ```com.twitter.finagle.RequestTimeoutException: exceeded 10.seconds to unspecified while dyn binding /http/1.1/GET/web. Remote Info: Not Available``` which is not very informative.  I wasted some time trying to figure out whether linkerd could even talk to namerd.  Simply stating that no response was received from namerd or that the response was in the wrong format would have been helpful.

* linkerd's dtab and /delegator screens in the admin interface failed to load.  No useful error was given.

* namerd showed no logging output even though I assume it had received an incorrectly formatted request on it's httpController port.  Also, there was no warning about a thriftController not being configured.  I would expect a warning since the primary use case is to be paired with linkerd.

* AFAIK, there is no mention in the documentation that the thriftController must be present to talk to linkerd.

**Comment by momania** [comment]
I've been looking into linkerd + namerd combination too and ran into the same issues.
I might add that I think in general the documentation is very unclear, and mostly not up to date with the implementation, and that the logging of both services is extremely bad. I case something doesn't work, the logs give no direction as to what the issue can be.

**Comment by adleong** [comment]
Hi @brendanyounger!  Sorry that you got tripped up on this.  This is a really common error so any suggestions on how to make this more user friendly would be appreciated.  I'll give you some background on each of your points.

* When linkerd sends a thrift request to namerd's http interface, namerd does not respond.  I'm not sure exactly why this is the case, perhaps at the protocol level an HTTP message is indistinguishable from an incomplete thrift request?  Normally we could just set a timeout on this request and fail it if namerd doesn't respond within the timeout but this interface uses long-polling where namerd isn't expected to respond until the data changes.  This makes setting a timeout impossible.  We could investigate exactly why namerd can't fail the request immediately when it receives a message of the wrong protocol but in the medium-term we want to move away from this thrift long-polling interface in favor of gPRC anyway (https://github.com/BuoyantIO/linkerd/issues/842).
* Adding a timeout on the delegator screen, on the other hand, makes total sense.  Issue is here: https://github.com/BuoyantIO/linkerd/issues/525.  PRs welcome :)
* I don't think a warning when the thrift namer interface is absent is appropriate because the other interfaces (http and eventually gRPC) can be used for naming (if the right interpreter is configured).
* The docs mention that briefly here https://linkerd.io/config/0.8.5/linkerd/index.html#namerd "The io.l5d.namerd interpreter uses namerd’s long-poll thrift interface and the io.l5d.namerd.http interpreter uses namerd’s HTTP streaming interface."  But I agree that this is pretty deeply buried and not 100% clear.  Suggestions and/or PRs for how to make this more clear are greatly appreciated.

Thanks for your interest in the project!
