### ISSUE TITLE
Add filter plugin interface

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd#828]
Linkerd users often wish to extend linkerd with custom authentication or rate-limiting logic.  Currently, this best way to do this is to build an identifier plugin that implements the custom logic (or calls out to an external service).  Unfortunately, this has some limitations:

* Identifiers cannot return custom error responses
* The custom logic may wish to know how the request will be identified (logical dst) or routed (concrete dst) and use this as input
* Chaining a custom identifier together with a more standard identifier (such as methodAndHost) is awkward and unintuitive

A finagle `Filter` is a more appropriate abstraction for implementing things such as authentication, rate-limiting, and request mutation.  

We should introduce a plugin interface to allow filter plugins which define a finagle filter.  Linkerd should insert these filters into the client stack so that they have access to logical and concrete dst information.

**Comment by olix0r** [comment]
I'm pretty staunchly against having a totally open-ended plugin interface, since it makes it _much_ harder to reason about what is going on in a request's lifecycle and how a filter behaves in the context of the rest of the stack (routing, retries, timeouts, etc). I really don't want to have to try to explain to users what is going on with arbitrary plugins in the mix.

I would much prefer to have an authentication plugin interface and a rate-limiting plugin interface (and etc) so we can be clear about the contract, use common interfaces, etc.

The need for something much more general than that isn't clear to me.

**Comment by halve** [comment]
+1 for a header modification interface. Maybe this is still to open-ended for you @olix0r ...

We are using linkerd in concert with nginx as an edge service. Nginx is mapping all the public paths to service urls, then l5d does its thing. We are hoping to move more responsibility to l5d like header modification. A simple plugin interface would be super slick.

**Comment by adleong** [comment]
Closing in favor of more purposeful plugin interfaces.
