### ISSUE TITLE
TTwitter thrift routing

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd#935]
Support routing based on the dst field which is present in ttwitter protocol thrift messages.

**Comment by masonoise** [comment]
We're looking forward to this. I wanted to suggest that if it's not much more difficult, rather than supporting routing specifically on one field, given that the TTwitter envelope can contain arbitrary key-value pairs it would be great if it's possible to route on any field. If that adds significant complexity then it's maybe a future enhancement, but I thought I'd mention it. Thx.

**Comment by adleong** [comment]
Thanks for the comment, @masonoise.  I think we can definitely support routing based on arbitrary request context field.  Quick question for you: how do you build your TTwitter thrift clients?  One thing I noticed was that even though the TTwitter header has field specifically for dest, finagle clients never set this field.

**Comment by masonoise** [comment]
We have a custom framework that's used by our clients -- I've asked someone else to chime in with any relevant details that they can provide. I'm not the expert on that part! Thanks.

**Comment by raydin** [comment]
I don't think you can populate the dest header field when using the standard Scala Finagle thrift client. It add the header using TTwitterClientFilter which does not populate this nor allows you to supply an initial version of the header.

**Comment by adleong** [comment]
@raydin that's correct, unfortunately.  The modified version of TTwitterClientFilter in this change does set the dest header.

**Comment by raydin** [comment]
@adleong, that would require forking finagle or creating a filter that deserializes the header and re-serializes it with the field set.
