### ISSUE TITLE
Collapsed clients don't show up on combined requests graph

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd#956]
Looking at the current admin dashboard, it appears that when a new collapsed client is added to the dashboard, that client's request stats don't show up in the combined requests graph. Only once the new client is expanded do its stats start to show up in the combined graph.

**Comment by adleong** [comment]
I think this might be intended behavior?  In the case where there are many many clients, they'll all start collapsed and not show up on the combined requests graph.  I don't think you'd ever want 100 lines on the combined graph, for example.  cc/ @rmars

**Comment by klingerf** [comment]
As far as I can tell, all of the initially loaded clients still show up in the graph, even if they start out collapsed. But any new client that is added in the collapsed state after the dashboard loads does not show up in the graph. I think that either a) no collapsed clients should show up in the graph, or b) all collapsed clients should show up in the graph. The current behavior where initially loaded collapsed clients show up and added collapsed clients do not seems broken.

**Comment by rmars** [comment]
Agreed with both of you - if we have 100 clients we probably don't want that many lines on the graph. But also, the behaviour should be consistent. I vote that no collapsed clients should show up in the graph.

The reason all the initially loaded clients show up on the combined client graph is because we call `router.clients()` in `combined_client_graph.js`. Shouldn't be too bad to unify the behaviour.
