### ISSUE TITLE
grpc interop: `ping_pong` fails

### ISSUE THREAD

**Issue by stevej** [linkerd/linkerd#980]
It currently hangs. I believe this is waiting for the deferred stream PR to land.

```/Users/stevej% ./go-grpc-interop-client -use_tls=false  -server_port=60001 -test_case=ping_pong```

**Comment by olix0r** [comment]
I think this is a bug in the test server and not grpc interop: https://github.com/linkerd/linkerd/pull/978#pullrequestreview-18535493

**Comment by olix0r** [comment]
Ok, so I improved the interop server implementation, but there's still a problem here: I think, due to flow control, linkerd isn't capable of buffering some of the larger body sizes.  Basically, linkerd is trying to buffer a ~45KB-sized message, it's read ~32KB, and the client stops sending additional frames... it seems likely that this is because the server hasn't opened the window further (because we use flow control to limit memory pressure).

At the very least, I think we'll need to expose better window size configuration so we can accommodate larger streams. (May be tricky to wire into netty, we'll see).

Note that this should not be any problem for grpc messages _transiting h2 routers_. This is purely for scala clients/servers generated with the grpc tools in this dir.

**Comment by stevej** [comment]
Yes, your fix does work for `empty_stream` but not for `ping_pong`

**Comment by olix0r** [comment]
Fixed in #1024
